// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOG_OUT = "LOG_OUT";

//MAasterlist
export const CURRENT_ML_FETCHED = "CURRENT_ML_FETCHED";
export const NO_CURRENT_ML = "NO_CURRENT_ML";
export const ML_DOCTORS_FETCHED = "ML_DOCTORS_FETCHED";
export const NO_ML_DOCTORS = "NO_ML_DOCTORS";
export const ML_CLEARED = "ML_CLEARED";
export const DOCTOR_DETAILS_FETCHED = "DOCTOR_DETAILS_FETCHED";
export const MASTERLIST_ADDED = "MASTERLIST_ADDED";
export const ADD_MASTERLIST_FAILED = "ADD_MASTERLIST_FAILED";
export const ML_DOCTOR_ADDED = "ML_DOCTOR_ADDED";
export const ML_DOCTOR_REMOVED = "ML_DOCTOR_REMOVED";
export const DATE_EXCLUDED = "DATE_EXCLUDED";
export const DATE_EXCLUDE_FAILED = "DATE_EXCLUDE_FAILED";
export const NO_CALL_ADDED = "NO_CALL_ADDED";
export const NO_CALLS_FETCHED = "NO_CALLS_FETCHED";
export const NO_CALLS_FETCH_FAILED = "NO_CALLS_FETCH_FAILED";
export const NO_CALL_CLEARED = "NO_CALL_CLEARED";
export const EXCLUDED_DATE_REMOVED = "EXCLUDED_DATE_REMOVED";
export const REMOVE_DATE_FAILED = "REMOVE_DATE_FAILED";
export const MASTERLIST_SENT = "MASTERLIST_SENT";
export const DCR_ADDED = "DCRS_ADDED";
export const DCR_ADD_FAILED = "DCR_ADD_FAILED";
export const DCR_FETCHED = "DCR_FETCHED";
export const ACTIVE_DCR_SET = "ACTIVE_DCR_SET";
export const DCR_DOCTORS_FETCHED = "DCR_DOCTORS_FETCHED";
export const ACTIVE_DCR_CLEAR = "ACTIVE_DCR_CLEAR";
export const DCR_DOCTOR_ADDED = "DCR_DOCTOR_ADDED";
export const DCR_DOCTOR_REMOVED = "DCR_DOCTOR_REMOVED";
export const DOCTOR_COUNT_UPDATED = "DOCTOR_COUNT_UPDATED";

//Doctors
export const DOCTORS_LOADED = "DOCTOR_LOADED";
export const LOAD_DOCTORS_FAILED = "LOAD_DOCTOR_FAILED";
export const DOCTORS_CLEARED = "DOCTORS_CLEARED";
export const DOCTOR_ADDED = "DOCTOR_ADDED";
export const DOCTOR_ADD_FAILED = "DOCTOR_ADD_FAILED";

//Medreps
export const MEDREP_ADDED = "MEDREP_ADDED";
export const ADD_MEDREP_FAILED = "ADD_MEDREP_FAILED";
export const MEDREPS_FETCHED = "MEDREPS_FETCHED";
export const NO_MEDREPS = "NO_MEDREPS";
export const MEDREPS_CLEARED = "MEDREPS_CLEARED";
